### ISSUE TITLE
Paper comments in pull request

### ISSUE THREAD

**Issue by benjaminbolling** [bwheelz36/ParticlePhaseSpace#146]
Comments on the paper itself, see https://github.com/bwheelz36/ParticlePhaseSpace/pull/145.

**Comment by benjaminbolling** [comment]
In Acknowledgements, a reference is made to "Image-X Institute". Please add more details on the institute (e.g. that it is part of the Faculty of Medicine and Health at the University of Sydney).

**Comment by bwheelz36** [comment]
Thank you! accepted
