### ISSUE TITLE
Automated test

### ISSUE THREAD

**Issue by benjaminbolling** [bwheelz36/ParticlePhaseSpace#149]
Please add a python script that automatically invokes the test scripts with multiple datasets producing a more complete report that is readable directly from the terminal.

**Comment by bwheelz36** [comment]
Hi @benjaminbolling  

If you type `pytest` into the repository root (assuming it is installed as per #148 !) then it will collect and run all tests, generating the below report. Does this address this issue? If not could you point me to an example of what you mean?


![image](https://github.com/bwheelz36/ParticlePhaseSpace/assets/64300337/6e58cb83-3ad3-4ce4-9775-fcf54c13415e)

**Comment by benjaminbolling** [comment]
My bad, I did not install the dev_requirements meaning pytest could not initiate (lots of missing packages).

Installed dev_requirements in the conda env for this package, pytest working as intended. Many thanks!
