### ISSUE TITLE
Paper: State of the field

### ISSUE THREAD

**Issue by benjaminbolling** [bwheelz36/ParticlePhaseSpace#151]
The "State of the field" is mentioned under "Statement of need". The application should also be compared to other already existing applications that also calculate phase space, with the results also compared - not only the p2sat and postpic codes, which ParticlePhaseSpace is "built upon". 

Regarding the statement "built upon", please elaborate a bit more.

**Comment by bwheelz36** [comment]
Hi @benjaminbolling 

> Regarding the statement "built upon", please elaborate a bit more.

So, what happened here was that I started working on this package independently, before discovering the [p2sat](https://github.com/lesnat/p2sat) package and realizing there was some substantial overlap. However, the p2sat package was also lacking some features like test cases, CI, and extension mechanisms. So I got in touch with Leo (author of that package and co-author on this paper) and essentially we figured out together which useful features in p2sat could be incorporated into this code. 

So, this is the long story of what I mean when I say "built upon"! Let me know if you think I should use different wording or be more elaborate.

> The application should also be compared to other already existing applications that also calculate phase space, with the results also compared - not only the p2sat and postpic code

We have done heuristic "sanity check" comparisons with p2sat, but what specifically would you like to see here?

**Comment by benjaminbolling** [comment]
Thanks for the explanation 🙂 

I would though also prefer to see a comparison to e.g. TraceWin (https://www.dacm-logiciels.fr/tracewin) and Synergia (https://synergia.fnal.gov), if possible

**Comment by bwheelz36** [comment]
So both of these programs are for simulating accelerators. This code could in theory enable one to write new `DataLoaders` or `DataExporters` that would enable genetic particle phase space data to be be imported/exported between these codes - so it's not possible to 'compare'. Also TraceWin is commerical software that I can't access. Synergia it looks like I could access, but it would be a long process to build from scratch - and even then, I couldn't actually carry out a comparison, I could only write a DataLoader to load some data from Synergia. For this point - if you have a file I can test on, I would be happy to do it, but tbh I don't really want to have to build synergia from scratch and then learn how to use it!

**Comment by benjaminbolling** [comment]
Sorry for the long waiting time for my reply.

Thanks for clarifying - it is probably my background in accelerator physics that made me want to attempt to compare the data to some software I am used to, but indeed, the applications are more for simulating accelerators rather than working with generic particle phase space data.
